services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Spread services.
    Bkstg\NoticeBoardBundle\Spread\:
        resource: '../../Spread'
        public: true
        tags:
            - { name: spy_timeline.spread }

    # Event subscribers.
    Bkstg\NoticeBoardBundle\EventSubscriber\PostTimelineSubscriber:
        tags:
            - { name: kernel.event_subscriber }
