services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\NoticeBoardBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    # Controller services.
    Bkstg\NoticeBoardBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: controller.service_arguments }

    # Spread services.
    Bkstg\NoticeBoardBundle\Spread\:
        resource: '../../Spread'
        public: true
        tags:
            - { name: spy_timeline.spread }

    # Doctrine event listeners.
    Bkstg\NoticeBoardBundle\EventListener\PostCreator:
        tags:
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
