services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Spread services.
    Bkstg\NoticeBoardBundle\Timeline\Spread\:
        resource: '../../Timeline/Spread'
        public: true
        tags:
            - { name: spy_timeline.spread }

    # Event subscribers.
    Bkstg\NoticeBoardBundle\Timeline\EventSubscriber\PostTimelineSubscriber:
        tags:
            - { name: kernel.event_subscriber }
